// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_DiagonalMovement","status":true,"description":"(v.1.5) Just a basic diagonal movement plugin. Written for compatibility with other Galv plugins.","parameters":{"Diagonal Mouse":"false","Diagonal Charset":"true","Diagonal Speed":"90","Block Diagonal":"false"}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"false","Made with MV Image":"MadeWithMv","Show Custom Splash":"true","Custom Image":"STUDIOtoaster","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"no_title_screen","status":true,"description":"","parameters":{}}
];
